<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4cc0cd84-fcb7-466a-ba48-f4d7f5c353e1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.12.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\NoodKa.Application\NoodKa.Application.csproj" />
    <ProjectReference Include="..\NoodKa.Infrastructure\NoodKa.Infrastructure.csproj" />
  </ItemGroup>

</Project>
